[package]
name = "mini-rv32ima-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
clap = { version =  "4.1.4", features = [ "derive" ] }
crossterm = "0.25.0"
